---
swagger: '2.0'
info:
  description: 'Tour of Heroes API'
  title: 'Tour Of Heroes'
  version: '1.0.0'
schemes:
  - https
paths:
  /{proxy+}:
    x-amazon-apigateway-any-method:
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses: {}
